In [35]:

import numpy as np 
import tensorflow as tf 
from tensorflow import keras
from keras.layers import SimpleRNN,Embedding
from keras.utils import pad_sequences

In [36]:
docs = [ 'go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai',
'inquilab zindabad'
]

In [37]:
tokenize = tf.keras.preprocessing.text.Tokenizer()
tokenize.fit_on_texts(docs)
tokenize.index_word

{1: 'india',
 2: 'jeetega',
 3: 'hip',
 4: 'ki',
 5: 'jai',
 6: 'kohli',
 7: 'sachin',
 8: 'dhoni',
 9: 'go',
 10: 'hurray',
 11: 'bhai',
 12: 'bharat',
 13: 'mata',
 14: 'modi',
 15: 'ji',
 16: 'inquilab',
 17: 'zindabad'}

In [38]:
sequesces = tokenize.texts_to_sequences(docs)
sequesces

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [39]:
sequesces = pad_sequences(sequesces,padding="post")
sequesces

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [50]:


# Create a Sequential model
model = tf.keras.Sequential()

# Add an Embedding layer
model.add(tf.keras.layers.Embedding(input_dim=len(tokenize.index_word)+1, output_dim=2))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
# Display the model summary
model.summary()


Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.compile('adam','accuracy')

In [49]:
model.get_weights()[0]

array([[ 0.00602865, -0.03288539],
       [ 0.03947176,  0.0268794 ],
       [ 0.03893964, -0.03429698],
       [-0.02680014, -0.03983754],
       [ 0.04147157,  0.03420199],
       [ 0.00440959,  0.04548777],
       [-0.04998624, -0.04526759],
       [-0.03294694,  0.04406265],
       [ 0.00567443,  0.02216823],
       [ 0.01480174, -0.0254536 ],
       [-0.00249092,  0.01458105],
       [-0.04685931,  0.0456298 ],
       [-0.00415572,  0.03907143],
       [ 0.04918016, -0.00439984],
       [ 0.0182617 , -0.01173682],
       [-0.02679716, -0.01801529],
       [-0.00402814, -0.00355492],
       [ 0.0207842 ,  0.03439024]], dtype=float32)

In [46]:
pred = model.predict(sequesces)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[ 0.01480174, -0.0254536 ],
        [ 0.03947176,  0.0268794 ],
        [ 0.00602865, -0.03288539],
        [ 0.00602865, -0.03288539],
        [ 0.00602865, -0.03288539]],

       [[ 0.03947176,  0.0268794 ],
        [ 0.03947176,  0.0268794 ],
        [ 0.00602865, -0.03288539],
        [ 0.00602865, -0.03288539],
        [ 0.00602865, -0.03288539]],

       [[-0.02680014, -0.03983754],
        [-0.02680014, -0.03983754],
        [-0.00249092,  0.01458105],
        [ 0.00602865, -0.03288539],
        [ 0.00602865, -0.03288539]],

       [[ 0.03893964, -0.03429698],
        [-0.04685931,  0.0456298 ],
        [ 0.03893964, -0.03429698],
        [ 0.03947176,  0.0268794 ],
        [ 0.03893964, -0.03429698]],

       [[-0.00415572,  0.03907143],
        [ 0.04918016, -0.00439984],
        [ 0.04147157,  0.03420199],
        [ 0.00440959,  0.04548777],
        [ 0.00602865, -0.03288539]],

       [[-0.04998624, -0.04526759],
        [-0.04998624, -0.04526759],
        [ 0.006028