<br>
<br>

# `#1. getting started with pytorch: `

<br>
<br>

In [5]:
import torch 
import tensorflow as tf
torch.__version__

'2.5.1+cu124'

---

<br>

# `#1.1 Introduction to tensor in pytorch: `

<br>

---

<br>

#### `1.1.1: scalar in tensorflow and troch: `

<br>

In [13]:
# scalar tensor in tensorflow:
scalar = tf.constant(8,dtype=tf.float64)
print(scalar)
print("data type:", scalar.dtype)
print("dimention: ", scalar.ndim)
print(type(scalar))

tf.Tensor(8.0, shape=(), dtype=float64)
data type: <dtype: 'float64'>
dimention:  0
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [14]:
# scalar tensor in torch 
scalar = torch.tensor(8,dtype=torch.float32)
print(scalar)
print(scalar.ndim)
print(scalar.dtype)
print(type(scalar))

tensor(8.)
0
torch.float32
<class 'torch.Tensor'>



<br>

#### `1.1.2 vector in tensorflow and torch: `

-> A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:

<br>

In [19]:
# vector in tensorflow: 
vector_rank_1 = tf.constant([1, 2, 3],dtype=tf.float32)
print(vector_rank_1)
print("dimention: ", vector_rank_1.ndim)
print("shape:", vector_rank_1.shape)
print(vector_rank_1.dtype)
print(type(vector_rank_1))

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
dimention:  1
shape: (3,)
<dtype: 'float32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [20]:
# vector in torch:
vector_rank_1 = torch.tensor([1,2,3],dtype=torch.int64)
print(vector_rank_1)
print("dimention: ", vector_rank_1.ndim)
print("shape:", vector_rank_1.shape)
print(vector_rank_1.dtype)
print(type(vector_rank_1))

tensor([1, 2, 3])
dimention:  1
shape: torch.Size([3])
torch.int64
<class 'torch.Tensor'>


<br>

#### `#1.1.3 matrix in tensorflow and torch: `
-> A "matrix" or "rank-2" tensor has two axes:
<br>

In [22]:

# matrix in tensorflow: 
matrix_rank_2 = tf.constant([[1,2],
                             [3,4],
                             [5,6]],dtype=tf.int8)

print(matrix_rank_2)
print("dimention: ", matrix_rank_2.ndim)
print("shape:", matrix_rank_2.shape)
print(matrix_rank_2.dtype)
print(type(matrix_rank_2))


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int8)
dimention:  2
shape: (3, 2)
<dtype: 'int8'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [23]:
# matrix in torch:
matrix_rank_2 = torch.tensor([[1,2],
                              [2,3],
                              [3,4]],dtype=torch.long)
print(matrix_rank_2)
print("dimention: ", matrix_rank_2.ndim)
print("shape:", matrix_rank_2.shape)
print(matrix_rank_2.dtype)
print(type(matrix_rank_2))


tensor([[1, 2],
        [2, 3],
        [3, 4]])
dimention:  2
shape: torch.Size([3, 2])
torch.int64
<class 'torch.Tensor'>


<br>

#### `#1.1.4 tensor in tensorflow and torch: `
-> grather than rank_2
<br>

In [24]:
#tensor with tensorflow: 
rank_3_tensors  = tf.constant([[[1,2,3],
                                [4,5,6]]],dtype=tf.int16)
print(rank_3_tensors)
print("dimention: ", rank_3_tensors.ndim)
print("shape:", rank_3_tensors.shape)
print(rank_3_tensors.dtype)
print(type(rank_3_tensors))


tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int16)
dimention:  3
shape: (1, 2, 3)
<dtype: 'int16'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [26]:
#tensor with tensorflow: 
rank_3_tensors  = tf.constant([[[1,2,3],
                                [4,5,6]],
                               [[1,2,3],
                                [4,5,6]]],dtype=tf.int16)
print(rank_3_tensors)
print("dimention: ", rank_3_tensors.ndim)
print("shape:", rank_3_tensors.shape)
print(rank_3_tensors.dtype)
print(type(rank_3_tensors))

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int16)
dimention:  3
shape: (2, 2, 3)
<dtype: 'int16'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [28]:
#tensor with pytorch: 
rank_3_tensors  = torch.tensor([[[1,2,3],
                                [4,5,6]],
                               [[1,2,3],
                                [4,5,6]]],dtype=torch.int64)
print(rank_3_tensors)
print("dimention: ", rank_3_tensors.ndim)
print("shape:", rank_3_tensors.shape)
print(rank_3_tensors.dtype)
print(type(rank_3_tensors))

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])
dimention:  3
shape: torch.Size([2, 2, 3])
torch.int64
<class 'torch.Tensor'>


<br>

# `#1.1.5 make random tensor in tensorflow and pytorch: `

<br>

In [44]:
#make a random tensor in tensorflow:
random_tensor = tf.random.uniform(shape=(3,1,4))
print(random_tensor)
print()
print("Dimention: ",random_tensor.ndim)

tf.Tensor(
[[[0.7927805  0.6472974  0.5189899  0.41505027]]

 [[0.9578258  0.29722786 0.1303531  0.05340147]]

 [[0.9496119  0.9112023  0.23980725 0.49721563]]], shape=(3, 1, 4), dtype=float32)

Dimention:  3


In [42]:

random_tensor = torch.rand(5,4,4)
print(random_tensor)
print()
print("Dimention: ", random_tensor.ndim)
print("Shape: ",random_tensor.shape)

tensor([[[0.1839, 0.2321, 0.6647, 0.7850],
         [0.7336, 0.7852, 0.2125, 0.4196],
         [0.5224, 0.5281, 0.0537, 0.2556],
         [0.7978, 0.8297, 0.8404, 0.4743]],

        [[0.9162, 0.7947, 0.8838, 0.1013],
         [0.5489, 0.4668, 0.1096, 0.3250],
         [0.5347, 0.5197, 0.8337, 0.3613],
         [0.1432, 0.0761, 0.6803, 0.2078]],

        [[0.8781, 0.0720, 0.3168, 0.0594],
         [0.9171, 0.7201, 0.7666, 0.9717],
         [0.1766, 0.3491, 0.8245, 0.7631],
         [0.6232, 0.0665, 0.2374, 0.9885]],

        [[0.9225, 0.9715, 0.8563, 0.1454],
         [0.6629, 0.9514, 0.9545, 0.6575],
         [0.1733, 0.9662, 0.4924, 0.4752],
         [0.3186, 0.7979, 0.3142, 0.1174]],

        [[0.5644, 0.3015, 0.0523, 0.2514],
         [0.1940, 0.7421, 0.6760, 0.7744],
         [0.2999, 0.9153, 0.8587, 0.4782],
         [0.9021, 0.7871, 0.7808, 0.7652]]])

Dimention:  3
Shape:  torch.Size([5, 4, 4])


<br>

# `#1.1.6 make zero and one tensor:  `

<br>

In [47]:
# with tensorflow: zero 

zero_tensor = tf.zeros(shape=(1,2,3),dtype=tf.float32)
print(zero_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)


In [48]:
#with tensorflow: one

one_tensor = tf.ones(shape=(2,3,4),dtype=tf.float32)
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [54]:
# with torch: zero
zero_tensor = torch.zeros(size=(1,2,3),dtype=torch.int8)
print(zero_tensor)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int8)


In [55]:
# with torch: one
one_tensor = torch.ones(size=(1,2,3),dtype=torch.int8)
print(one_tensor)

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int8)


<br>

# `#1.1.7 tensor with arrange: `

<br>

In [58]:
# with tensorflow:

tensor_arrange = tf.range(start=0,limit=10,delta=1)
print(tensor_arrange)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [60]:
# with pytorch:
tensor_arrange = torch.arange(start=1,end=20)
print(tensor_arrange)

tensor_arrange = torch.range(start=0,end=10,step=2)
print(tensor_arrange)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])
tensor([ 0.,  2.,  4.,  6.,  8., 10.])


/tmp/ipykernel_62843/426032705.py:5: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_arrange = torch.range(start=0,end=10,step=2)


<br>
<br>

# `#1.1.8 make ones or zeros, tensor like: `

<br>
<br>

In [61]:
# with tensorflow: 
image = tf.random.uniform(shape=(5,3,4))
zero_like = tf.zeros_like(image)
print(zero_like)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(5, 3, 4), dtype=float32)


In [63]:
# with pytorch:
image = torch.rand(size=(5,3,4),dtype=torch.float16)
one_like = torch.ones_like(image)
print(one_like)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float16)


<br>
<br>

# `#1.1.8 make indentity matrix with tensorflow and pytorch`

<br>
<br>

In [64]:
# with tensorflow: 
identity = tf.eye(4)
print(identity)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [65]:
# with pytorch:
identity  = torch.eye(5)
print(identity)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


<br>
<br>

# `1.1.9 make a tensor with same value tensorflow and pytorch: `

<br>
<br>

In [72]:
# with tensorflow:
full_tensor = tf.fill(dims=(2,5,2),value=3)
print(full_tensor)

tf.Tensor(
[[[3 3]
  [3 3]
  [3 3]
  [3 3]
  [3 3]]

 [[3 3]
  [3 3]
  [3 3]
  [3 3]
  [3 3]]], shape=(2, 5, 2), dtype=int32)


In [69]:
# with tensorflow:
full_tensor = torch.full(size=(3,3),fill_value=5)
print(full_tensor)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


<br>
<br>

# `#1.1.10: equally distributaed number: (when we line: )`
<br>
<br>

In [77]:
#with tensorflow:
line_space = tf.linspace(start=1,stop=8,num=5)
print(line_space)

tf.Tensor([1.   2.75 4.5  6.25 8.  ], shape=(5,), dtype=float64)


In [76]:
#with torch: 
line_space = torch.linspace(start=1,end=10,steps=5,dtype=torch.int8)
print(line_space)

tensor([ 1,  3,  5,  7, 10], dtype=torch.int8)


<br>
<br>

# `# 1.2 Datatype: `

<br>
<br>


`Back propagation and Forward propagation এর সময়, আমাদের ভ্যালু গুলো point(0.001) আকারে পরিবর্তন হয় । যদি, আমাদের data type high হয় তাহলে আমরা অনেক accurate value store করতে পারি । like: float32 এর চেয়ে float64 এ accurate ভ্যালু পাওয়া যাবে । পাশাপাশি, computation float32 এর থেকে float64 slow হয় । `


In [80]:

# change data type in tensorflow and see the ::device:;
tensor_float32 = tf.random.uniform(shape=(3,5),minval=0,maxval=10)
tensor_float32.dtype


tf.float32

In [88]:
tensor_float64 = tf.cast(tensor_float32,dtype=tf.float64)
print(tensor_float64.dtype)
print(tensor_float64.device)

<dtype: 'float64'>
/job:localhost/replica:0/task:0/device:CPU:0


In [85]:


# change data type in pytorch and ::device::

tensor_float32 = torch.rand(size=(3,4),dtype=torch.float16)
print(tensor_float32.dtype)
tensor_float64 = tensor_float32.type(dtype=torch.float32)
print(tensor_float64.dtype)


torch.float16
torch.float32


In [86]:
tensor_float64.device

device(type='cpu')

<br>
<br>

# `# 1.3 Mainipulating tensors(tensor operation:)`

- ### `Addition`
- ### `Subtraction`
- ### `multiplication (element wize)`
- ### `matrix multiplication `

<br>
<br>

In [93]:

# with tensorflow: 

a = tf.fill(dims=(3,3),value=5)
b = tf.fill(dims=(3,3),value=5)
print(a)
print(b)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [94]:
tf.add(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [95]:
tf.subtract(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [96]:
tf.multiply(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]], dtype=int32)>

In [97]:
tf.divide(a,b)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

In [98]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[75, 75, 75],
       [75, 75, 75],
       [75, 75, 75]], dtype=int32)>

In [102]:

# with pytorch: 
a = torch.full(size=(3,3),fill_value=5)
b = torch.full(size=(3,3),fill_value=5)

print("addition: ", torch.add(a,b))
print()

print("subtraction: ",torch.subtract(a,b))
print()

print("multiplication (element wize): ",torch.multiply(a,b))
print()

print("divition: ",torch.divide(a,b))
print()


print("matrix_multiplication: ",torch.matmul(a,b))
print()

addition:  tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

subtraction:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

multiplication (element wize):  tensor([[25, 25, 25],
        [25, 25, 25],
        [25, 25, 25]])

divition:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

matrix_multiplication:  tensor([[75, 75, 75],
        [75, 75, 75],
        [75, 75, 75]])



<br>
<br>

# `# 1.4: Tanspose of a matrix: `

<br>
<br>

In [105]:

# in tensorflow: 
a = tf.fill(dims=(2,3),value=9)
print(a)
print()
print("transpose: ",tf.transpose(a))

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)

transpose:  tf.Tensor(
[[9 9]
 [9 9]
 [9 9]], shape=(3, 2), dtype=int32)


In [106]:

# in pytorch: 
b = torch.full(size=(2,4),fill_value=4)
print(b)
print()
print("Transpose: ",b.T)


tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])

Transpose:  tensor([[4, 4],
        [4, 4],
        [4, 4],
        [4, 4]])


<br>
<br>

# `# 1.5 Find max,min,mean,sum: `

<br>
<br>

In [128]:

# with tensorflow:

a = tf.linspace(start=1,stop=10,num=5)
print("a: ", a)
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(tf.reduce_mean(a))
print(tf.reduce_sum(a))


a:  tf.Tensor([ 1.    3.25  5.5   7.75 10.  ], shape=(5,), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(10.0, shape=(), dtype=float64)
tf.Tensor(5.5, shape=(), dtype=float64)
tf.Tensor(27.5, shape=(), dtype=float64)


In [129]:

# with pytorch:

a = torch.linspace(start=1,end=10,steps=5)
print("a: ",a)
print(a.min())
print(a.max())
print(a.mean())
print(a.sum())

a:  tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor(1.)
tensor(10.)
tensor(5.5000)
tensor(27.5000)


<br>
<br>

# `# 1.6 positional min and max: `

[1, 3, 5, 7, 8]:

positional min: -> min: 1 and it's index: 0

positional max: -> max: 8 and it's index: 4

<br>
<br>

In [130]:

# with tensorflow: 
tensor_a = tf.constant([2,4,12,-1,3,4,5,122])
print("positoin of minimum val: ",tf.argmin(tensor_a))
print("positoin of minimum val: ",tf.argmax(tensor_a))


positoin of minimum val:  tf.Tensor(3, shape=(), dtype=int64)
positoin of minimum val:  tf.Tensor(7, shape=(), dtype=int64)


In [132]:

# with pytorch 
tensor_a = torch.tensor([2,4,12,-1,3,4,5,122])
print("positoin of minimum val: ",tensor_a.argmin())
print("positoin of minimum val: ",tensor_a.argmax())


positoin of minimum val:  tensor(3)
positoin of minimum val:  tensor(7)


<br>
<br>

# `# 1.7 Reshaping, Stacking, Squeezing, Unsqueezing, Permute: `

<br>
<br>

<br>

## `1.7.1 with tensorflow:` 

<br>

In [169]:


tensor_a = tf.constant([[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]])

print(tensor_a.shape)


(3, 4)


In [138]:
# reshaping:
print(tf.reshape(tensor=tensor_a,shape=(6,2)))
print()
print(tf.reshape(tensor=tensor_a,shape=(2,6)))

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [140]:

# stacking: Stacking combines multiple tensors along a new dimension:
print(tf.stack(values=[tensor_a,tensor_a],axis=0)) # along a new axis 0(row) #dim: 3D
print()
print(tf.stack(values=[tensor_a,tensor_a],axis=1)) # along a new axis 1(column) #dim: 3D


tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(2, 3, 4), dtype=int32)

tf.Tensor(
[[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 9 10 11 12]]], shape=(3, 2, 4), dtype=int32)


In [162]:

# squeezing: remove dimention with size 1
print(tensor_a.shape)
tensor_a = tf.expand_dims(input=tensor_a,axis=0)
print()
print(tensor_a)
print()
print()
print(tf.squeeze(input=tensor_a))
print()
print()

(1, 1, 1, 1, 1, 3, 4)

tf.Tensor(
[[[[[[[[ 1  2  3  4]
       [ 5  6  7  8]
       [ 9 10 11 12]]]]]]]], shape=(1, 1, 1, 1, 1, 1, 3, 4), dtype=int32)


tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)




In [170]:

# Unsqueezing:
print(tf.expand_dims(input=tensor_a,axis=1))
print()
print(tf.expand_dims(input=tensor_a,axis=0))
print()
print(tf.expand_dims(input=tensor_a,axis=-1))
print()

tf.Tensor(
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]], shape=(3, 1, 4), dtype=int32)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(1, 3, 4), dtype=int32)

tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]], shape=(3, 4, 1), dtype=int32)



In [172]:

# Permuting (Transpose)
print(tensor_a.shape)
print()
print(tf.transpose(tensor_a))
print()


(3, 4)

tf.Tensor(
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]], shape=(4, 3), dtype=int32)



<br>

## `1.7.2 with pytorch:` 

<br>

In [174]:

tensor_a = torch.tensor([[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]])
print(tensor_a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [179]:

# reshaping: 
print(tensor_a.reshape(2,6))
print()

# staking: 
print(torch.stack(tensors=[tensor_a,tensor_a],dim=0),torch.stack(tensors=[tensor_a,tensor_a],dim=0).shape)
print()
print(torch.stack(tensors=[tensor_a,tensor_a],dim=1),torch.stack(tensors=[tensor_a,tensor_a],dim=1).shape)
print()

#squeezing


tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]) torch.Size([2, 3, 4])

tensor([[[ 1,  2,  3,  4],
         [ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [ 9, 10, 11, 12]]]) torch.Size([3, 2, 4])



<br>

## `1.7.3  view() in pytorch:` 

<br>