<br>
<br>

# `#1 ONE HOT ENCODING WITH (ML Base Techinique: LECTURE_72)`

<br>
<br>

In [1]:
import numpy as np 
from sklearn.preprocessing import OneHotEncoder

In [2]:

corpus = ["People watch campusx",
         "campusx watch campusx",
        "People write comment",
        "campusx write comment" ]


print(corpus)
print("shape: ",corpus.shape)

['People watch campusx', 'campusx watch campusx', 'People write comment', 'campusx write comment']


AttributeError: 'list' object has no attribute 'shape'

In [3]:
corpus = np.array(corpus)
print(corpus)
print(corpus.shape)

['People watch campusx' 'campusx watch campusx' 'People write comment'
 'campusx write comment']
(4,)


In [4]:
corpus = corpus.reshape(-1,1)
corpus.shape

(4, 1)

In [43]:
oneHotEncoder = OneHotEncoder(sparse_output=False)
ans = oneHotEncoder.fit_transform(corpus)
print(ans)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
